### ISSUE TITLE
How can I add my own dictioanry for searching on goldendict (not Zen)

### ISSUE THREAD

**Issue by eresdf** [kanjieater/GoldenDict-Toolbelt#3]
I use this site
https://dict.naver.com/rukodict/#/main

Is it possible to do?

Thank you!

**Comment by kanjieater** [comment]
The nice thing about GoldenDict is you don't need my add-on to do that! You can just write your own to add whatever sites you are interested it. So yes, it is possible, but it's not part of my Japanese learning process so I won't add it currently.
